services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hyeyum-ai
    depends_on:
      - weaviate
    ports:
      - "${AI_PORT:-8000}:8000"
    environment:
      APP_NAME: ${APP_NAME:-hyeyum-ai}
      APP_ENV: ${APP_ENV:-prod}
      ROOT_PATH: ${ROOT_PATH:-/ai}
      UPLOAD_DIR: ${UPLOAD_DIR:-uploads}
      MAX_UPLOAD_FILE_SIZE_MB: ${MAX_UPLOAD_FILE_SIZE_MB:-100}
      WEAVIATE_URL: ${WEAVIATE_URL:-http://weaviate:8080}
      WEAVIATE_GRPC_HOST: ${WEAVIATE_GRPC_HOST:-weaviate:50051}
    volumes:
      - ./uploads:/app/uploads
    networks:
      - hyeyum-network
    restart: unless-stopped

  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.38.3
    container_name: hyeyum-weaviate
    ports:
      - "${WEAVIATE_PORT:-8081}:8080"
      - "${WEAVIATE_GRPC_PORT:-50051}:50051"
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: ${WEAVIATE_QUERY_DEFAULTS_LIMIT:-25}
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: ${WEAVIATE_ANONYMOUS_ACCESS_ENABLED:-true}
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      CLUSTER_HOSTNAME: node1
      OPENAI_APIKEY: ${OPENAI_API_KEY:-}
    networks:
      - hyeyum-network
    restart: unless-stopped

volumes:
  weaviate_data:

networks:
  hyeyum-network:
    external: true
